FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY MediaInAction ./MediaInAction
WORKDIR /src/MediaInAction/services/cmskit/src/MediaInAction.CmskitService.HttpApi.Host
RUN dotnet publish -c Release -o bin/Release/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /src/MediaInAction/services/cmskit/src/MediaInAction.CmskitService.HttpApi.Host/bin/Release/publish/ .
ENTRYPOINT ["dotnet", "MediaInAction.CmskitService.HttpApi.Host.dll"]