// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using MediaInAction.TraktService.TraktMethods;
using System.Collections.Generic;

// ReSharper disable once CheckNamespace
namespace MediaInAction.TraktService.Controllers.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ITraktMethodAppService), typeof(TraktMethodClientProxy))]
public partial class TraktMethodClientProxy : ClientProxyBase<ITraktMethodAppService>, ITraktMethodAppService
{
    public virtual async Task<List<TraktMethodDto>> GetListAsync()
        {
            return await RequestAsync<List<TraktMethodDto>>(nameof(GetListAsync));
        }
}
