config:
  selfUrl: https://mia-st-public-web
  gatewayUrl: https://mia-st-gateway-web-public
  authServer:
    authority: http://mia-st-authserver
    requireHttpsMetadata: "false"
    isOnProd: false
    metaAddress: #
  dotnetEnv: Staging
  redisHost: mia-st-redis
  rabbitmqHost: mia-st-rabbitmq
  elasticsearchHost: mia-st-elasticsearch
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  

ingress:
  host: mia-st-public-web
  tlsSecret: mia-wildcard-tls

image:
  repository: mia/app-publicweb
  tag: latest
  pullPolicy: IfNotPresent

env: {}
