FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY MediaInAction ./MediaInAction
WORKDIR /src/MediaInAction/gateways/web-public/src/MediaInAction.WebPublicGateway
RUN dotnet publish -c Release -o bin/Release/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0  AS final
WORKDIR /app
COPY --from=build /src/MediaInAction/gateways/web-public/src/MediaInAction.WebPublicGateway/bin/Release/publish/ .
ENTRYPOINT ["dotnet", "MediaInAction.WebPublicGateway.dll"]