// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using MediaInAction.EmbyService.Services;

// ReSharper disable once CheckNamespace
namespace MediaInAction.EmbyService.Services.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IEmbyAppService), typeof(EmbyClientProxy))]
public partial class EmbyClientProxy : ClientProxyBase<IEmbyAppService>, IEmbyAppService
{
    public virtual async Task<EmbyDto> GetAsync(Guid? anonymousUserId)
    {
        return await RequestAsync<EmbyDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid?), anonymousUserId }
        });
    }

    public virtual async Task<EmbyDto> AddProductAsync(AddProductDto input)
    {
        return await RequestAsync<EmbyDto>(nameof(AddProductAsync), new ClientProxyRequestTypeValue
        {
            { typeof(AddProductDto), input }
        });
    }

    public virtual async Task<EmbyDto> RemoveProductAsync(RemoveProductDto input)
    {
        return await RequestAsync<EmbyDto>(nameof(RemoveProductAsync), new ClientProxyRequestTypeValue
        {
            { typeof(RemoveProductDto), input }
        });
    }
}
