config:
  selfUrl: # https://mia-st-basket
  corsOrigins: # https://mia-st-gateway-web,https://mia-st-gateway-public-web,https://mia-st-public
  connectionStrings:
    administrationService: #
  authServer:
    authority: http://mia-st-authserver
    requireHttpsMetadata: "false"
    metadataAddress: http://mia-st-keycloak:8080
    swaggerClientId: "WebGateway_Swagger"
  dotnetEnv: Staging
  redisHost: mia-st-redis
  rabbitmqHost: mia-st-rabbitmq
  elasticsearchHost: mia-st-elasticsearch
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  remoteServices:
    catalogBaseUrl: #
    catalogGrpcUrl: #

ingress:
  host: mia-st-basket
  tlsSecret: mia-wildcard-tls

image:
  repository: mia/service-basket
  tag: latest
  pullPolicy: IfNotPresent

env: {}
    