config:
  selfUrl: # https://mia-st-ordering
  corsOrigins: # https://mia-st-gateway-web,https://mia-st-gateway-public-web
  connectionStrings:
    orderingService: #
    administrationService: #
  authServer:
    authority: http://mia-st-authserver
    requireHttpsMetadata: "false"
    metadataAddress: http://mia-st-keycloak:8080
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: mia-st-redis
  rabbitmqHost: mia-st-rabbitmq
  elasticsearchHost: mia-st-elasticsearch
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

ingress:
  host: mia-st-ordering
  tlsSecret: mia-wildcard-tls

image:
  repository: mia/service-ordering
  tag: latest
  pullPolicy: IfNotPresent

env: {}
    