FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY MediaInAction ./MediaInAction
WORKDIR /src/MediaInAction/apps/public-web/src/MediaInAction.PublicWeb
RUN dotnet publish -c Release -o bin/Release/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0  AS final
WORKDIR /app
COPY --from=build /src/MediaInAction/apps/public-web/src/MediaInAction.PublicWeb/bin/Release/publish/ .
ENTRYPOINT ["dotnet", "MediaInAction.PublicWeb.dll"]